### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by XfaonXE** [lucasburlingham/shalissa#1]
i cant get on discord today but um, when i pullsite it dont pull xenonmc.xyz/XFRAME too, cus rn ur serve is on php 7 irequire 8,so instead i went to config and set ignore-php version to true but when i goto site and look at config.json after pulling nothin happsn

**Comment by lucasburlingham** [comment]
I will manually pull the repository changes. Please do not contact me through Github Issues, but rather email me at lucas.burlingham@icloud.com or support@xenonmc.xyz, as this goes directly to both of us.

**Comment by XfaonXE** [comment]
Have no acces to my email on school device, rn im on remote desktop but that wont always be the case  Sent from Mail for Windows 10 From: Lucas BurlinghamSent: Wednesday, March 3, 2021 12:55 PMTo: lucasburlingham/shalissaCc: XfaonXE; AuthorSubject: Re: [lucasburlingham/shalissa] hi (#1) I will manually pull the repository changes. Please do not contact me through Github Issues, but rather email me at lucas.burlingham@icloud.com or support@xenonmc.xyz, as this goes directly to both of us.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
